# Generated by Django 2.1.4 on 2019-02-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodReceipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_title', models.CharField(max_length=100, null=True)),
                ('learn_content', models.TextField(max_length=1000, null=True)),
                ('learn_image_image', models.ImageField(blank=True, null=True, upload_to='book-image')),
            ],
        ),
    ]
