# Generated by Django 2.1.4 on 2019-02-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodReceipes', '0002_auto_20190204_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreceipts',
            name='learn_pre_content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
