# Generated by Django 2.1.4 on 2019-02-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodReceipes', '0003_foodreceipts_learn_pre_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodreceipts',
            old_name='learn_image_image',
            new_name='learn_image',
        ),
    ]
