# Generated by Django 2.1.4 on 2019-02-10 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodReceipes', '0004_auto_20190204_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_comment', models.TextField(max_length=150, null=True)),
                ('learn_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('learn_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodReceipes.FoodReceipts')),
                ('learn_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
