# Generated by Django 2.1.4 on 2019-02-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinfo',
            name='info_content',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
