# Generated by Django 2.1.4 on 2019-02-04 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodInfo', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='info_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodInfo.FoodInfo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='info_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='info_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
