# Generated by Django 2.1.4 on 2019-02-04 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodInfo', '0004_auto_20190204_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='info_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodInfo.FoodInfo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='info_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
