# Generated by Django 2.1.4 on 2019-02-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodInfo', '0006_auto_20190211_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='info_comment',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
